### ISSUE TITLE
snap

### ISSUE THREAD

**Issue by graingert** [runelite/launcher#58]
create a snapcraft snap for runelite: https://snapcraft.io/runelite

**Comment by MrCarroll** [comment]
I've been using Snapcraft to publish the rslauncher snap for a few months now. Based on the feedback I've gotten, it's a very good fit for RuneLite.

I've published a hidden snap to the Snap store now, so if people could go and test it that would be fantastic. Particular things to test for are sound functionality and GPU support. However, info of any real divergence between the .jar/appimage would be appreciated. Since the Snap is currently sandboxed, it will write all data to ~/snap/runelite/ as $HOME is redefined. It is possible to ensure $HOME matches the true $HOME, but this would require some tweaks to the launcher itself due to Snap quirks. This means features such as automatic screenshots on level up will write to ~/snap/runelite/ rather than ~/pictures 

**sudo snap install runelite**

Canonical provide a build service that may be useful for keeping the Snap up to date, however it is very easy to do local builds anyway, assuming snapd is installed

sudo snap install snapcraft --classic
snapcraft
sudo snap install **built_local_snap_name.snap** --dangerous

The dangerous flag is needed for any snaps lacking signature verification, which is provided automatically when uploaded to the Snap Store.

Having a Snap build provides atomic upgrades, sandboxing, cross platform support, and on systems with full integration for Snap, easy one click installation (E.G, Ubuntu + Gnome software). As such, I think it's a good offering alongside the AppImage already provided

https://github.com/MrCarroll/launcher/tree/snapcraft

**Comment by Adam-** [comment]
added in #69
